import re
from dataclasses import dataclass, field


@dataclass
class VulnFeatures:
    response_code: int = 0
    response_length: int = 0
    has_error_keyword: bool = False
    has_stacktrace: bool = False
    has_db_error: bool = False
    has_sql_keyword: bool = False
    has_command_output: bool = False
    has_file_read: bool = False
    has_jndi_error: bool = False
    has_auth_bypass: bool = False
    has_version_leak: bool = False
    has_default_creds: bool = False
    has_sensitive_data: bool = False
    content_type_match: bool = False
    payload_reflected: bool = False
    response_time_anomaly: bool = False
    feature_vector: list = field(default_factory=list)

    def to_vector(self) -> list:
        return [
            self.response_code,
            min(self.response_length, 100000),
            int(self.has_error_keyword),
            int(self.has_stacktrace),
            int(self.has_db_error),
            int(self.has_sql_keyword),
            int(self.has_command_output),
            int(self.has_file_read),
            int(self.has_jndi_error),
            int(self.has_auth_bypass),
            int(self.has_version_leak),
            int(self.has_default_creds),
            int(self.has_sensitive_data),
            int(self.content_type_match),
            int(self.payload_reflected),
            int(self.response_time_anomaly),
        ]


ERROR_KEYWORDS = [
    "exception", "error", "stacktrace", "traceback",
    "caused by", "at org.", "at com.", "at java.",
]

STACKTRACE_PATTERNS = [
    r"at\s+[\w.]+\([\w.]+\.java:\d+\)",
    r"java\.lang\.\w+Exception",
    r"org\.apache\.\w+",
    r"org\.springframework\.\w+",
    r"Traceback \(most recent call last\)",
    r"File \"[^\"]+\", line \d+",
]

DB_ERROR_KEYWORDS = [
    "sql syntax", "mysql", "postgresql", "oracle", "sqlite",
    "jdbc", "syntax error", "ORA-", "SQLSTATE", "ERROR 1064",
    "unclosed quotation mark", "unterminated quoted string",
]

SQL_KEYWORDS = [
    "select ", "insert ", "update ", "delete ", "union ", "from ",
    "where ", "order by", "group by", "having ", "drop table",
]

COMMAND_OUTPUT_PATTERNS = [
    r"uid=\d+\(\w+\)\s+gid=\d+",
    r"root:\w+:\d+:\d+:",
    r"Linux\s+\S+\s+\d+\.\d+",
    r"Windows\s+(NT|Version)\s+\d+",
    r"Microsoft Windows \[",
]

FILE_READ_PATTERNS = [
    r"root:.*:0:0:",
    r"\[boot loader\]",
    r"# This file is automatically generated",
    r"127\.0\.0\.1\s+localhost",
]

JNDI_ERROR_KEYWORDS = [
    "javax.naming", "NamingException", "JNDI",
    "ldap://", "rmi://", "InitialContext",
    "lookup", "DataSource", "JndiDataSourceFactory",
]

SENSITIVE_PATTERNS = [
    r"(?:password|passwd|pwd)\s*[=:]\s*\S+",
    r"(?:api[_-]?key|apikey)\s*[=:]\s*\S+",
    r"(?:secret|token)\s*[=:]\s*\S+",
    r"(?:jdbc|datasource)[_-]?url\s*[=:]\s*\S+",
    r"(?:AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}",
]


def extract_features(response_text: str, response_code: int = 0,
                     response_headers: dict = None, payload: str = "") -> VulnFeatures:
    features = VulnFeatures()
    features.response_code = response_code
    features.response_length = len(response_text)
    features.content_type_match = "application/json" in (response_headers or {}).get("content-type", "")

    text_lower = response_text.lower()

    features.has_error_keyword = any(kw in text_lower for kw in ERROR_KEYWORDS)

    for pattern in STACKTRACE_PATTERNS:
        if re.search(pattern, response_text, re.IGNORECASE):
            features.has_stacktrace = True
            break

    features.has_db_error = any(kw in text_lower for kw in DB_ERROR_KEYWORDS)
    features.has_sql_keyword = any(kw in text_lower for kw in SQL_KEYWORDS)

    for pattern in COMMAND_OUTPUT_PATTERNS:
        if re.search(pattern, response_text):
            features.has_command_output = True
            break

    for pattern in FILE_READ_PATTERNS:
        if re.search(pattern, response_text):
            features.has_file_read = True
            break

    features.has_jndi_error = any(kw in text_lower for kw in JNDI_ERROR_KEYWORDS)
    features.has_auth_bypass = response_code == 200 and any(
        kw in text_lower for kw in ["admin", "dashboard", "management", "console"]
    )
    features.has_version_leak = any(
        kw in response_text for kw in ["Server:", "X-Powered-By:", "X-AspNet-Version:"]
    )
    features.has_default_creds = any(
        kw in text_lower for kw in ["default password", "default credentials", "change password"]
    )

    for pattern in SENSITIVE_PATTERNS:
        if re.search(pattern, response_text, re.IGNORECASE):
            features.has_sensitive_data = True
            break

    if payload and len(payload) > 3:
        payload_clean = payload[:100]
        if payload_clean in response_text:
            features.payload_reflected = True

    features.feature_vector = features.to_vector()
    return features
