from app.scanner.modules import spring4shell
from app.scanner.modules import spring_spel
from app.scanner.modules import spring_actuator
from app.scanner.modules import spring_cloud_gateway
from app.scanner.modules import spring_cloud_function
from app.scanner.modules import shiro_deserialization
from app.scanner.modules import shiro_auth_bypass
from app.scanner.modules import log4j2_jndi
from app.scanner.modules import fastjson_rce
from app.scanner.modules import nacos_auth_bypass
from app.scanner.modules import nacos_rce
from app.scanner.modules import druid_unauth
from app.scanner.modules import tomcat_manager_unauth
from app.scanner.modules import struts2_ognl
